## M. van Oijen (2024). Bayesian Compendium, 2nd edition.
## Chapter 8. MCMC and Multivariate Models

  library(mvtnorm)

  EXPOL5 <- function( t=0, b=c(10,1,0.007,2,1) ) {
    I0  <- b[1] ; K <- b[2] ; LAR <- b[3] ; LUE <- b[4] ; W0 <- b[5] 
    W   <- log( 1 + exp(I0*K*LAR*LUE*t) * (exp(K*LAR*W0)-1) ) / (K*LAR)
    LAI <- W * LAR
    return( list( "W"=W, "LAI"=LAI ) ) }

  bmin5  <- c(9.9,0.5,0.005,1,0.5)         ; bmax5 <- c(10.1,1.5,0.009,3,1.5)
  range5 <- bmax5 - bmin5                  ; var5  <- (range5^2) / 12
  mb     <- rowMeans( cbind(bmin5,bmax5) ) ; Sb    <- diag( var5 )

  t_W      <- c(20,60,100) ; y_W <- c(10,500,1200) ; sd_W <- c(5,15,120)
  t_L      <- c(20,80,100) ; y_L <- c(0.2,5,4)     ; sd_L <- c(0.1,1,1)
  data_W   <- cbind( t=t_W, y=y_W, sd=sd_W )
  data_LAI <- cbind( t=t_L, y=y_L, sd=sd_L )
  data     <- list( "W"=data_W, "LAI"=data_LAI )

  logPrior <- function( b, mb.=mb, Sb.=Sb ) { dmvnorm( b, mb., Sb., log=T ) }

  logLikList <- function( b, dataList, f.=f ) {
    sum( sapply( names(dataList), function(v){ sum(
      dnorm( f.( dataList[[v]][,1], b ) [[v]],
             mean=dataList[[v]][,2], sd=dataList[[v]][,3], log=T ) ) } ) ) }

  logPostList <- function( b, mb.=mb, Sb.=Sb, dataList, f.=f ) {
    logPrior(b, mb., Sb.) + logLikList(b, dataList, f.) }

  MetropolisLogPost <- function( f.=f, logp=logPost, b0=mb, SProp=Sb/100, ni.=ni, ... ) {
    bChain <- matrix( NA, nrow=ni., ncol=length(b0) ) ; bChain[1,] <- b0
    for( i in 2:ni. ) {
       b1  <- bChain[i-1,] + as.numeric( rmvnorm(1,sigma=SProp) ) 
       if( log(runif(1)) < logp(b1,f.=f.,...) - logp(b0,f.=f.,...) )
            bChain[i,] <- b0 <- b1
       else bChain[i,] <- b0 }
    return(bChain) }

  ni <- 3e4
  
  set.seed(1)

  bChain <- MetropolisLogPost( f=EXPOL5, logp=logPostList, dataList=data )

# Bayesian calibration of the 5-parameter expolinear model ($\\texttt{EXPOL5}$)
# by means of Metropolis sampling.
  par( mfrow = c(5,2), mar=c(2,2.5,1.5,1) )
  plot(bChain[,1],pch=".") ; hist(bChain[,1],yaxt="n",main="I0" )
  plot(bChain[,2],pch=".") ; hist(bChain[,2],yaxt="n",main="K"  )
  plot(bChain[,3],pch=".") ; hist(bChain[,3],yaxt="n",main="LAR")
  plot(bChain[,4],pch=".") ; hist(bChain[,4],yaxt="n",main="LUE")
  plot(bChain[,5],pch=".") ; hist(bChain[,5],yaxt="n",main="W0" )

# Time series of biomass (W) and leaf-area index (LAI), generated by the
# expolinear equation using the posterior mean parameter vector (thick line) and
# 20 parameter vectors subsampled from the MCMC (thin dashed lines).
  par( mfrow = c(1,2), mar=c(4,2,2,2) )
  mb5_y    <- colMeans(bChain)
  varName1 <- expression( 'W (kg m'^-2*')' )
  varName2 <- expression( 'LAI (m'^2*' m'^-2*')' )
  varNames <- c( varName1, varName2 )
  p        <- floor( seq(5e3, ni, length.out=20) )
  for(v in 1:2) {
    t.y    <- data[[v]][,"t"]
    y      <- data[[v]][,"y"]
    t.plot <- seq( min(t.y), max(t.y), length.out=20 )
    plot  ( t.plot, sapply( t.plot, function(i){EXPOL5(i,mb5_y)[[v]]} ),
            ylim=c(0,1.3*max(y)), xlab="Time (days)", ylab="",
            main=varNames[v], lwd=3, type="l" )
    points( data[[v]], col='blue', lwd=3, cex=2 )
    for(j in 1:20) { points( t.plot, sapply( t.plot,
      function(i){EXPOL5(i,bChain[p[j],])[[v]]} ), lwd=0.5, type="l", lty=2 ) }
  }

  Sb5_y <- cov(bChain) ; Rb5_y <- cor(bChain)
